TILE_SIZE = 32
TILE_SCALING = 1
TILES_WIDTH = 40
TILES_HEIGHT = 23
SCREEN_WIDTH = TILE_SIZE * TILE_SCALING * TILES_WIDTH
SCREEN_HEIGHT = TILE_SIZE * TILE_SCALING * TILES_HEIGHT
SCREEN_TITLE = "Ladders Runner"
GRAVITY = 0.5
PLAYER_SPEED = 6
LADDER_SPEED = 3
PLAYER_JUMP_SPEED = 9
ANIMATION_FRAME_TIME = 0.1
PLAYER_MAX_HEALTH = 100
DAMAGE_LAYER_DAMAGE = 5
DAMAGE_2_LAYER_DAMAGE = 20
TRANSPORTATION_SPEED = 10
BACKGROUND_COLOR = (135, 206, 235)
UI_TEXT_COLOR = (0, 0, 0)
UI_FONT_SIZE = 24
UI_FONT_NAME = "Arial"

ZOOM_CAM = 1.50

ENEMY_MAX_HEALTH = 50
ENEMY_SHOOT_COOLDOWN = 2.0
BULLET_DAMAGE = 5
BULLET_SPEED = 8
BULLET_LIFETIME = 5.0
SCREEN_MARGIN = 100

JUMP_POWER = 12
COLLECTIBLE_ANIMATION_SPEED = 0.1
#PLAYER_IDLE_TEXTURE = "assets/sprites/Players/1/1 Biker/Biker_attack1_c/Biker_attack1_1.png"
JUMP_ANIMATION_SPEED = 0.1


WEAPON_ANIMATION_SPEED = 0.05
PLAYER_BULLET_SPEED = 10
PLAYER_BULLET_LIFETIME = 2.0

SHOOT_TIMER = 0
SHOOT_COOLDOWN = 0.2
LEVEL_WIDTH = 1275
LEVEL_HEIGHT = 1000